apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: This task will clean up a workspace by deleting all the files.
  workspaces:
    - name: source
  steps:
    - name: remove
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        if [ -d "${WORKSPACE_SOURCE_PATH}" ]; then
          #Delete non-hidden files and directories
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e

        echo "Upgrading pip..."
        python -m pip install --upgrade pip wheel

        echo "Installing dependencies from requirements.txt..."
        pip install -r requirements.txt

        echo "Running nosetests..."
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8-custom
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.9-slim
      workingDir: $(workspaces.source.path) 
      script: |
        #!/bin/bash
        set -e

        echo "Upgrading pip..."
        python -m pip install --upgrade pip wheel

        echo "Installing dependencies from requirements.txt..."
        pip install -r requirements.txt

        echo "Running flake8 on service..."
        flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics --max-complexity=10 --max-line-length=127